@host = http://85.215.71.124

###

POST {{host}}/register/createUser HTTP/1.1
Content-Type: application/json

{
    "username": "Joel"
}

###

POST {{host}}/register/registerUser HTTP/1.1
Content-Type: application/json

{
    "username": "Joel",
    "password": "JoelStink*100",
    "email": "joel@starkov.com",
    "firstName": "Joel",
    "lastName": "Starkov"
}

###

PUT {{host}}/register/addPoint HTTP/1.1
Content-Type: application/json

{
    "username": "deine Mum"
}

###


GET {{host}}/register/getPoints HTTP/1.1
Content-Type: application/json

{
    "username": "Moritz"
}

###

GET  {{host}}/register/allUsers HTTP/1.1